### ISSUE TITLE
It always runs on Node 16 Which is failing the merge task

### ISSUE THREAD

**Issue by nagesheaton** [selfagency/merge-coverage#2]
I explicitly set up the environment variable in Runner for Node 18 but still it is taking 16

=======================================
Run actions/setup-node@v4
  
Attempt to resolve the latest version from manifest...
Resolved as '[18](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:13:19).20.4'
Found in cache @ /opt/hostedtoolcache/node/18.20.4/x64
Environment details
  node: v18.[20](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:13:21).4
  npm: 10.7.0
  yarn: 1.22.22
  
=======================================
Run echo "$(dirname $(which node))" >> $GITHUB_PATH
  echo "$(dirname $(which node))" >> $GITHUB_PATH
  shell: /usr/bin/bash -e ***0***

=======================================
Run selfagency/merge-coverage@v1.1.2
  with:
    source: /home/runner/work/cloud-iot-platform-ts-datafromadx/cloud-iot-platform-ts-datafromadx
    coverage-reports: /home/runner/work/cloud-iot-platform-ts-datafromadx/cloud-iot-platform-ts-datafromadx/coverage/UnitTest/*/coverage.cobertura.xml
  /home/runner/work/cloud-iot-platform-ts-datafromadx/cloud-iot-platform-ts-datafromadx/coverage/service.UnitTest/*/coverage.cobertura.xml
  
    output-folder: /home/runner/work/cloud-iot-platform-ts-datafromadx/cloud-iot-platform-ts-datafromadx/coverage/merged
    formats: lcov
    artifacts: true

Run actions/setup-node@v3
Found in cache @ /opt/hostedtoolcache/node/16.[2](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:15:2)0.2/x64
Environment details
  node: v16.20.2
  npm: 8.19.4
  yarn: 1.22.22
Run actions/github-script@v6
Run npm i -g nyc
  
npm WARN EBADENGINE Unsupported engine ***
npm WARN EBADENGINE   package: 'nyc@17.0.0',
npm WARN EBADENGINE   required: *** node: '>=18' ***,
npm WARN EBADENGINE   current: *** node: 'v16.20.2', npm: '8.19.4' ***
npm WARN EBADENGINE ***
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated rimraf@[3](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:15:3).0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
added 152 packages, and audited 153 packages in [4](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:15:4)s
15 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
Run actions/github-script@v6
  
SyntaxError: Invalid or unexpected token
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:1[5](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:15:5)143:16)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:26)
    at /home/runner/work/_actions/actions/github-script/v[6](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:15:6)/dist/index.js:1521[7](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:15:7):1
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15268:3
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15271:12)
    at Module._compile (node:internal/modules/cjs/loader:135[8](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:15:8):14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:[10](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:15:10))
    at Module.load (node:internal/modules/cjs/loader:[12](https://github.com/etn-ccis/cloud-iot-platform-ts-datafromadx/actions/runs/10455767233/job/28951514185#step:15:12)08:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
Error: Unhandled error: SyntaxError: Invalid or unexpected token

**Comment by nagesheaton** [comment]
Could you please help me to understand the failure and to fix it asap.

**Comment by selfagency** [comment]
The action has been upgraded to use Node 20.
